<h1>Visit Us</h1>

<p>There are a number of weekly events held by the CSMC that you're welcome to drop by! Unless otherwise noted, the location is the CS conference room, King 225. The schedule is for Fall 2018.</p>

<h2>CSMC Office Hours</h2>

<p>The CSMC holds office hours most days of the week. Feel free to stop by with questions about either computer science topics or the CS department/major!</p>


<h3>Monday</h3>
	<ul>
	<li>11a&ndash;11:30a: Andrew Li</li>
	<li>1p&ndash;1:30p: Leah Yassky</li>
	<li>2p&ndash;2:30p: Jane Hsieh</li>
</ul>

<h3>Tuesday</h3>
<ul>
	<li>2p&ndash;2:30p: Tumas Račkaitis</li>
	<li>2:30p&ndash;3p: Daniel Firebanks</li>
</ul>

<h3>Wednesday</h3>
<ul>
        <li>11a&ndash;11:30a: Andrew Li</li>
        <li>1p&ndash;2p: Maxwell Addae</li>
        <li>2p&ndash;2:30p: Jane Hsieh</li>
        <li>2:30p&ndash;3p: Daniel Firebanks</li>
</ul>

<h3>Thursday</h3>
<ul>
        <li>1p&ndash;2p: Jack Bens</li>
        <li>2p&ndash;2:30p: Tumas Račkaitis</li>
</ul>


<h3>Friday</h3>
<ul>
        <li>11a&ndash;11:30a: Andrew Li</li>

</ul>


<h2>Interview Practice</h2>

<p>We hold practice sessions to help prepare students for technical interviews you might encounter applying for software jobs or internships. In these sessions we typically work through sample problems in small groups.</p>

<h3>Saturday</h3>
<ul>
        <li>8a&ndash;12p</li>
</ul>

<h3>Sunday</h3>
<ul>
        <li>1p&ndash;4p</li>
</ul> 
