<h1>Git Night 2017</h1>
<p>Come learn the basics of git and GitHub! The event is at <em>4:30p on Friday, February 17</em> in King 135. Install git on your computer and bring it with, or use a lab machine to follow along.</p>
<p>If you'd like to participate in the GitHub activity to apply your git skills, send us your GitHub username before the event (to <code>jbregsto</code> or <code>jcornell</code> at <code>oberlin.edu</code>).</p>
<p><i>Hosted by Puck Bregstone and Jakob Cornell</i></p>
