<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.2.5 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Tue, 09 Feb 2010 17:55:12 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: Oberlin College Computer Science [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Oberlin College Computer Science';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'csmc';
$cfg['Servers'][$i]['password'] = 'okuzoh9Dai';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['AllowRoot'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = '4b71e77d8cb3b1.74661782';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>